update first view
SweetnessDark/blaz-robar pull request #3
Opened 2021-06-04 17:31 UTC by SweetnessDark

2021-06-11 15:34 UTC, dkolesnychenko requested changes

2021-06-11 15:34 UTC, dkolesnychenko commented on app/scss/components/banner.scss
> +        margin-left: 78px;
Исправить (вынести паддинг на .container)

2021-06-11 15:34 UTC, dkolesnychenko commented on app/scss/components/banner.scss
> +        margin-bottom: 63px;
не дублируй свойства. Можно написать вверху "margin: 0 0 63px";

2021-06-11 15:34 UTC, dkolesnychenko commented on app/scss/components/banner.scss
> +            right: 223px;
Используй паддинги на контейнере

2021-06-11 16:00 UTC, SweetnessDark commented on app/scss/components/banner.scss
> +            right: 223px;
Сделал

2021-06-11 16:00 UTC, SweetnessDark commented on app/scss/components/banner.scss
> +        margin-left: 78px;
Сделал

2021-06-16 15:00 UTC, dkolesnychenko approved these changes

2021-06-16 15:53 UTC, merged