update link portfolio
SweetnessDark/blaz-robar pull request #5
Opened 2021-06-05 15:43 UTC by SweetnessDark

2021-06-11 15:42 UTC, dkolesnychenko requested changes

2021-06-11 15:42 UTC, dkolesnychenko commented on app/index.html
> +     <div class="text-link">
Добавить .container

2021-06-11 15:42 UTC, dkolesnychenko commented on app/scss/components/background-link.scss
> +    width: 228px;
Убери отсюда и задавай ширину и высоту в тех секциях, где нужно

2021-06-11 15:42 UTC, dkolesnychenko commented on app/scss/components/text-link.scss
> +    background-color: #27212c;
Вынести цвет на родительский блок

2021-06-12 10:14 UTC, SweetnessDark commented on app/index.html
> +     <div class="text-link">
Сделал

2021-06-12 10:14 UTC, SweetnessDark commented on app/scss/components/text-link.scss
> +    background-color: #27212c;
Сделал

2021-06-16 15:21 UTC, dkolesnychenko approved these changes

2021-06-16 16:14 UTC, merged